/**
 * Constants of Actions.
 */

export const COUNTER_INCREASE = "COUNTER_INCREASE";
export const COUNTER_DECREASE = "COUNTER_DECREASE";

export const COUNTER_INCREASE_ASYNC = "COUNTER_INCREASE_ASYNC";
export const COUNTER_DECREASE_ASYNC = "COUNTER_DECREASE_ASYNC";
